### PR TITLE
TMI Changes / Client Builder / JavaDoc

### PR DESCRIPTION
**Pull request by stachu540**
### Prerequisites
* [x] I have read and understood the [contribution guidelines](CONTRIBUTING.md)
* [x] This pull request follows the code style of the project
* [x] I have tested this feature

### Changes Proposed
* [x] TMI Parser
* [x] Documented TMI
* [x] new Client Builder with methods `build()` and `login()` - second one connecting to the Twitch Chat and PubSub
* [x] new Dispatcher for `tmi`'s like
* [x] fixing errors by javadoc:
  * [x] replenishing empties returns or variables
  * [x] make undocumented constructors, methods, package-info's etc.

### Additional notes
This PR is reference to #15 Changes for Parsing IRC-WS is completed.

### CODE REVIEW

**Comment by stachu540** [comment]
Added documentation for All TMI environment expected listener. I guess you want to make your own listener? If you want, I'll make it for you.

**Comment by PhilippHeuer** [comment]
I like your work so far, you can add the listeners too. I would like to split it and create a single listener class for each event type that gets triggered using the EventDispatcher - the old irc parser class was way to long/confusing.

**Comment by PhilippHeuer** [comment]
Sure just do it when you have time. It might be even easier if we add a `RawIrcMessageEvent` and listen to it like all other events using the EventManager - no idea why i didn't think about that before.

I think i will add a example for ChannelMessages to show what i mean.

**Comment by stachu540** [comment]
If you have a time check #17 - for IRC-WS improvements (with some additional listener action) Will be similar like tmi.js

**Comment by PhilippHeuer** [comment]
I added a sample with the ChannelMessages, i would like to add the remaining events in the same fashion aswell.

**Comment by stachu540** [comment]
Implementing samples Emitters.

Now i can start writing listener.

**Comment by stachu540** [comment]
Dispatcher not done yet. I need to figure it out, what to do next. for mostly, looks very well but it's not tested yet.

**Comment by stachu540** [comment]
Done. time to take some JavaDoc'ing methods

**Pull request merged**
